apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-keydream-world
  namespace: keydream-world
  labels:
    app: keydream-world
spec:
  selector:
    matchLabels:
      app: keydream-world
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: keydream-world
    spec:
      containers:
      - name: keydream-world
        image: devcliff/keydream-world
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: docker-reg