apiVersion: v1
kind: Service
metadata:
  name: keydream-world-service
  namespace: keydream
spec:
  selector:
    app: keydream
  ports:
    - protocol: UDP
      name: udp
      port: 81
      targetPort: 80
